### ISSUE TITLE
Platform throws OutOfMemoryError on large files encryption

### ISSUE THREAD

**Issue by maxcotech** [hugo-pcl/native-crypto-flutter#2]
I was really grateful when I stumbled on this solution as it was as fast as I ever wanted to get in encryption and decryption of files. 

I could encrypt pictures even small video files in milliseconds. But then when I tried to encrypt files larger than 50 mb I realized it threw an OutOfMemoryError on both the emulator (genymotion Google pixels API 29) and on my real device (Tecno Spark 4 API 29).

I suspected this may have been due to the fact that I loaded all of the files onto the encrypt / decrypt functions at once using file.readAsBytes() .

So I decided to encrypt the files in chunks using stream and iosink. But then I realized that each encryption iteration generates a different IV. Which makes it impossible to decrypt the file after encrypt.

 Please is there any solution to this such as using externally generated IV in the encryption process for the purpose of consistency ?

**Comment by hugo-pcl** [comment]
Thank you very much for your feedback!

Indeed it's a bug on the Android platform. 🤔 (Maybe due to the limitations of Java ?? I don't know at all).

Your idea could be the right one. 😊 Split the data into chunks and associate a different IV to each chunk. But **don't create** a single IV and use it for all chunks.

To do that I have to correct the encryption process, and modify a little the decryption to be able to decrypt chunks easily.

Thanks again for your feedback, I'll try to propose a fix quickly.

**Comment by maxcotech** [comment]
You are welcome sir. You might want to take a look at CipherOutputStream and CipherInputStream classes in javax.crypto I think they were created for such purpose. 

If you are comfortable with it , I can add classes for chunked encryption and decryption in your kotlin and dart codes then make a pull request to you.

**Comment by hugo-pcl** [comment]
Cross-platform file encryption (android/ios) has been added in version 0.2.0
