### ISSUE TITLE
Help upgrading to the new version of the package

### ISSUE THREAD

**Issue by riverscuomo** [hugo-pcl/native-crypto-flutter#5]
Thank you for the incredibly fast cryptography Library. I'm trying to upgrade to the new version of the library to help us get around errors on Android when decrypting large files. For some reason I can't seem to get it to work even for small files. Can you see anything wrong here? `oldNativeDecrypt `is the method we used to decrypt files with the old version of this Library. It always worked fine, apart from the very large files. `nativeDecrypt `is the method I'm trying to implement with the new version of your library. I always get this error
```
[log] PlatformException(native_crypto, error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT, null, null)
`I/flutter ( 5756): [NativeCryptoException/platform_throws] [NativeCryptoException/unknown] error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
```
![image](https://user-images.githubusercontent.com/24362267/229359282-6db7db0d-814d-4996-af23-4662ea57621f.png)

**Comment by dv30fps** [comment]
If the old version is 0.0.6 and the new is 0.1.1, then the two are incompatible with each other. Files encrypted with 0.0.6 use AES CBC mode, whereas 0.1.1 uses AES GCM. If you encrypted some files with 0.0.6, you will not be able to decrypt them with 0.1.1 because 0.1.1 does not support AES CBC.

**Comment by riverscuomo** [comment]
@dv30fps Thank you for the response. The files are actually encrypted on the server with a Ruby package. I'm almost certain they're using AES GCM but let me confirm.

**Comment by dv30fps** [comment]
Note that AES GCM is an encryption method, not a file format. Since the encryption is done by another party, you would need to find the file format it uses and extract the components that Native Crypto's class CipherText calls iv, data, and tag. An example of a file format the one used by the AES Crypt software: https://www.aescrypt.com/aes_file_format.html , but it not the only one.

**Comment by hugo-pcl** [comment]
Hello, I've started to develop this package again after your discussion (and finally added file encryption ✨). I also added some documentation specifying the format of the messages expected by NativeCrypto.

Indeed, as @dv30fps said, the last versions of NativeCrypto use the GCM mode instead of CBC, which was not specified in the documentation before. Moreover the expected format is specific:

```
+------------------+--------------------+------------------+
| Nonce (12 bytes) | Cipher text (n-28) |  Tag (16 bytes)  |
+------------------+--------------------+------------------+
```

If your data comes from an external source, check that the format is correct, or reformat your message before passing it to NativeCrypto.

Anyway, thank you very much for your feedback. And don't hesitate if you have any other questions! 😊

**Comment by riverscuomo** [comment]
@hugo-pcl thank you so much. We are a small team of volunteers who inherited the codebases for the ruby server and the flutter app from someone who knows a lot more about cryptography than we do. But between us we should be able to figure out if we're meeting these specifications. I'll let you know what we come up with.

**Comment by riverscuomo** [comment]
Here is a simplified version of the file encryption code, in Ruby. This was working with the old `native_crypto`. Do you see any reason why it wouldn't be working with the new `native_crypto`?

```ruby
# Sends an encrypted audio file.
#
# @param path [String] the file path of the audio file
# @param filename [String] the name of the audio file
# @param password [String] the password to encrypt the file with
def send_encrypted_audio(path, filename, password)
  # Generate the salt for the encryption key
  hash_key = "REDACTED"
  omit = password[0,5].gsub('-','').chars.uniq.join
  salt = hash_key.reverse.gsub(Regexp.new("[#{omit}]"),'') + filename[0,10]

  # Create the encryption key using PBKDF2
  hash = OpenSSL::Digest::SHA256.new
  len = hash.digest_length
  key = OpenSSL::PKCS5.pbkdf2_hmac(password, salt, 10000, len, hash)

  # Initialize the AES-256-GCM cipher for encryption
  cipher = OpenSSL::Cipher.new('aes-256-gcm').encrypt
  cipher.key = key
  cipher.padding = 0
  iv = cipher.random_iv
  cipher.auth_data = 'REDACTED'

  # Create a binary StringIO object to store the encrypted data
  data = StringIO.new
  data.set_encoding Encoding::BINARY
  buf = String.new ""

  # Write the IV to the beginning of the encrypted data
  data << iv

  # Encrypt the audio file in 4KB chunks and write to the StringIO object
  File.open(path, 'rb') do |inf|
    while inf.read(4096, buf)
      data << cipher.update(buf)
    end
    data << cipher.final
  end

  # Write the authentication tag to the end of the encrypted data
  data << cipher.auth_tag

  # Set the Content-Length header and send the encrypted data as a response
  response.headers['Content-Length'] = data.size.to_s
  send_data(data.string, filename: filename, type: 'application/octet-stream')
end

rescue_from PortalFetchError do |exception|
  render json: exception.res.body, status: exception.res.code
end

rescue_from ActiveRecord::RecordNotFound do |exception|
  respond_to do |format|
    format.html { render "errors/not_found" }
    format.json { render status: 404, json: { message: "Not Found" } }
  end
end
```

**Comment by hugo-pcl** [comment]
Hi, 
the problem comes from `auth_data`, NativeCrypto uses AES GCM, but doesn't support AAD yet (which is data that is not encrypted but whose integrity is checked using the tag). Here is your example code that I modified a bit and executed, (some values are hardcoded in order to be fully matched to the NativeCrypto example application) the decryption is done without problem on Android.

```ruby
# Sends an encrypted audio file.
#
# @param path [String] the file path of the audio file
# @param filename [String] the name of the audio file
# @param password [String] the password to encrypt the file with
def send_encrypted_audio(path, filename, password)
  # Generate the salt for the encryption key
  #hash_key = "REDACTED"
  #omit = password[0,5].gsub('-','').chars.uniq.join
  #salt = hash_key.reverse.gsub(Regexp.new("[#{omit}]"),'') + filename[0,10]

  # HARDCODE SALT ('salt' as its the default salt in NativeCrypto example app)
  salt = 'salt'

  # Create the encryption key using PBKDF2
  hash = OpenSSL::Digest::SHA256.new
  len = hash.digest_length
  # Use 1000 iterations to be the same as in NativeCrypto example app
  key = OpenSSL::PKCS5.pbkdf2_hmac(password, salt, 1000, len, hash)

  puts key.unpack('H*').first

  # Initialize the AES-256-GCM cipher for encryption
  cipher = OpenSSL::Cipher.new('aes-256-gcm').encrypt
  cipher.key = key
  cipher.padding = 0
  iv = cipher.random_iv
  # Not supported by NativeCrypto
  #cipher.auth_data = 'REDACTED'

  # Create a binary StringIO object to store the encrypted data
  #data = StringIO.new
  #data.set_encoding Encoding::BINARY
  #buf = String.new ""
  data = ''

  # HARDCODE MESSAGE ('abc' as its the test string in NativeCrypto example app)
  message = 'abc'

  # Write the IV to the beginning of the encrypted data
  data << iv

  puts "Nonce length (should be 12): #{iv.length}"

  # Encrypt the audio file in 4KB chunks and write to the StringIO object
  #File.open(path, 'rb') do |inf|
  #  while inf.read(4096, buf)
  #    data << cipher.update(buf)
  #  end
  #  data << cipher.final
  #end

  data << cipher.update(message) + cipher.final

  # Write the authentication tag to the end of the encrypted data
  data << cipher.auth_tag

  puts "Tag length (should be 16): #{cipher.auth_tag.length}"

  # Set the Content-Length header and send the encrypted data as a response
  #response.headers['Content-Length'] = data.size.to_s
  #send_data(data.string, filename: filename, type: 'application/octet-stream')

  puts hexString = data.unpack('H*').first
end

send_encrypted_audio('path', 'filename', 'password')
```

In this example I encrypt the message `abc` with a key derived via a PBKDF2 using the password `password`, the salt `salt` and 1000 iterations.

<img width="492" alt="Capture d’écran 2023-04-06 à 15 20 14" src="https://user-images.githubusercontent.com/25439050/230390777-e5dae98b-4799-4ee8-b9ee-d9dc9ed5a8c0.png">

And here is the result on the example application, by copying the ciphertext generated by the Ruby code (without `auth_data`)

You can find the example here <https://github.com/hugo-pcl/native-crypto-flutter/tree/master/packages/native_crypto/example>

To replace the `auth_data`, you can encrypt it with the message (if it is not too big).
Hope to have helped you. Don't hesitate if you have any other questions!

**Comment by riverscuomo** [comment]
Fantastic. We will revise our `send_encrypted_audio` accordingly and see how it goes.

**Comment by riverscuomo** [comment]
Just dropping a note to say my server-side partner is not available to help me with this experiment until this Friday, April 14. We'll let you know what happens then. 

I do have a question in the meantime: I noticed you commented out our block that encrypted our message in chunks of 4096 bytes. Was that simply because your message was so short? Will we still be able to encrypt our messages in chunks as we did before? Also, does the chunking on the encryption side have nothing to do with the chunking on the decryption side? Or is it important that they match up in terms of chunk size?

**Comment by hugo-pcl** [comment]
Ok, can't wait to hear from you.

I commented it because, in my case the message being only a small string, it was not useful. However it won't change for you, you will still be able to encrypt your file by pieces. Be careful not to confuse this with NativeCrypto's chunks (which are 32MB by default), which were implemented to solve a memory problem on smartphones, which have a different Nonce for each chunk! 
So to answer your question: yes you can still encrypt in chunks. No, the server chunks have nothing to do with NativeCrypto chunks. 

> Note: If you use the `decrypt` method you have to check that the NativeCrypto chunk size is set to be larger than the file, otherwise it will try to chunk it when decrypting (and will try to find a nonce and a tag for each chunk...). I advise you to use `decryptFile` now (which doesn't have this problem of chunking in 32MB chunks anymore).

**Comment by riverscuomo** [comment]
Ah that's very helpful! We were trying to modify `native_crypto_flutter `to decrypt in 4096 byte chunks to match our encryption method. Good to know that's not necessary.

Ultimately, I believe we will have to use the `decrypt` method because we need to chunk our large files to avoid the memory problem. That's actually why were trying to upgrade to this latest version of the package. The old version was working great except for the large files which were giving us an 'out of memory' error.

**Comment by hugo-pcl** [comment]
NativeCrypto chunks the message like this: `[nonce1|chunk1|tag1][nonce2|chunk2|tag2]...[nonceN|chunkN|tagN]`. Because the method used to address the memory problem requires different ciphers for each chunk, and for security reasons you should never reuse the same nonce.

Here, what you call chunks (on the server), are pieces of the message that you add to the SAME cipher (`cipher.update`) as you use the cipher in stream mode. In the end you have a message like this: `[nonce|(piece 1)(piece 2)...(piece N)|tag]`.

Then you have 2 solutions:
- Fix the server-side encryption: encrypt the X bytes chunks independently of the others to be the same format as NativeCrypto. And be consistent with the size of the NativeCrypto chunks you will decrypt on the client side (you can configure the size when you initialize the NativeCrypto [AES cipher](https://github.com/hugo-pcl/native-crypto-flutter/blob/cab2843706fa8f0ce71aef15a5d134713b9a4326/packages/native_crypto/lib/src/ciphers/aes/aes.dart#L38))
- Keep the current server-side encryption, but download the message as a file (temp folder? documents?) and manipulate `File` in Dart and use the `decryptFile` method

keep in mind that if you continue to use the `decrypt` method, according to my tests, on some devices you will have memory problems on chunks larger than 32MB.

**Comment by riverscuomo** [comment]
Ok, I think we've been doing the second option: downloading the message into an encrypted file into the temporary folder.  Then when the user presses play on the audio player, we decrypt and play the file. 

Do I understand correctly that if we stick with option 2 (`decryptFile` ), we won't be able to do the decryption in chunks? I'm not seeing anything about chunking in the `decryptFile` method:

![image](https://user-images.githubusercontent.com/24362267/231812527-d539627f-ca85-4a98-9eae-ea16c43e95d6.png)

If that's the case, then we'd still encounter memory errors for our largest encrypted files. So we'll need to go with option 1, correct? The we can decrypt files of any size in chunks, so long as
- we encrypt with this pattern: `nonce1|chunk1|tag1][nonce2|chunk2|tag2]...[nonceN|chunkN|tagN]`
- we use the same chunk size on server and client
- we check that the chunk size is set to be larger than the file

**Comment by hugo-pcl** [comment]
Hello, it seems to me coherent.

No, the NativeCrypto chunk decryption is only there to solve the memory problem that comes from the communication between the Flutter engine and the native layers (swift and kotlin). If you use `decryptFile` no file, or memory is moved from the flutter memory to the native layers because you just give a path to the file you want to decrypt (file that you have previously downloaded and stored on your device with a package like https://github.com/xclud/dart_download for example), then the native layer takes care of opening, reading the file and decrypting it (with a stream cipher if you go to the kotlin implementation) so any memory problem is (normally) solved.

So by using `decryptFile` you don't have to change your server side implementation. Because everything can be encrypted with a single nonce (without splitting into pieces smaller than 32MB). Is this clearer?

Hoping to have helped you!

**Comment by riverscuomo** [comment]
Yep, that's pretty clear. Thanks! So our flutter client method would look something like the  `AESCubit.decryptFile` method in your example? https://github.com/hugo-pcl/native-crypto-flutter/blob/cab2843706fa8f0ce71aef15a5d134713b9a4326/packages/native_crypto/example/lib/presentation/cipher/blocs/aes/aes_cubit.dart#L329

**Comment by hugo-pcl** [comment]
Yes, I think it will be similar. Unless you don't use a BLoC, or Filepicker, but the idea is the same. 😊

**Comment by riverscuomo** [comment]
Okay, I think I'm pretty close. We're not using BLoC or Filepicker but I think I'm pretty much doing the same thing here.

![image](https://user-images.githubusercontent.com/24362267/232228584-f6067a86-20f6-4ce7-857b-7be9d636d72a.png)

We're still getting the bad decrypt error, though. Do you see anything wrong in our implementation above?

```
I/flutter ( 6788): error: PlatformException(IOException, java.io.IOException: javax.crypto.AEADBadTagException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT, Cause: javax.crypto.AEADBadTagException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT, Stacktrace: java.io.IOException: javax.crypto.AEADBadTagException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
I/flutter ( 6788): 	at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:133)
I/flutter ( 6788): 	at javax.crypto.CipherInputStream.read(CipherInputStream.java:202)
I/flutter ( 6788): 	at fr.pointcheval.native_crypto_android.ciphers.AES.decryptFile(AES.kt:138)
I/flutter ( 6788): 	at fr.pointcheval.native_crypto_android.NativeCrypto.decryptFile(NativeCrypto.kt:116)
I/flutter ( 6788): 	at fr.pointcheval.native_crypto_android.NativeCryptoAPI$Companion.setUp$lambda$22$lambda$21(Pigeon.kt:288)
I/flutter ( 6788): 	at fr.pointcheval.native_crypto_android.NativeCryptoAPI$Companion.$r8$lambda$o7wMJyBDQ0B9QInOzlOobRpTptw(Unknown Source:0)
I/flutter ( 6788): 	at fr.pointcheval.native_crypto_android.NativeCryptoAPI$Companion$$ExternalSyntheticLambda9.onMes
I/flutter ( 6788): FormatException: Unexpected character (at character 1)
I/flutter ( 6788): ëØBãÌã&êHë¤ù«ÅìyéÂvW±{ÇÉ[_SþD­þP^YõN9í|­ô¤÷ÒÔåÎ.	uk¾ó ÔÓë...
I/flutter ( 6788): ^
```

**Comment by greg0x** [comment]
I am working on tackling this problem. This exception supposedly comes from the `auth_data`/`aad`/`mac` 
https://docs.ruby-lang.org/en/master/OpenSSL/Cipher.html#class-OpenSSL::Cipher-label-Authenticated+Encryption+and+Associated+Data+-28AEAD-29

I have hardcoded aad into AES.kt `cipherInstance!!.updateAAD(byteArrayOf(<byte values of auth data from the previous version of native crypto>))` but still got the same error. 

Moving on to using the example app and running the ruby encryption myself. 

Note: implementing the chunking doesn't seem so hard after all this :)

**Comment by greg0x** [comment]
@hugo-pcl I have tried the ruby code and the example app just like you [here](https://github.com/hugo-pcl/native-crypto-flutter/issues/5#issuecomment-1499064718)

~~It seems that the example app is buggy because it needs to encrypt something and then decrypt its output and NOT the pasted string. I haven't tested this deeply yet, but if it behaves the same way for you then using the same `abc` string in the ruby script as the default placeholder in the app could have led to a false positive result in your testing.~~

~~Will dig deeper later into this.~~

Edit: 

The app is not buggy, I just didn't understand that I need the `External CipherText`.
The good news is that something WORKS :) Now we need to cut through the rest of the layers to find the issue.

**Comment by riverscuomo** [comment]
Just as a sanity check I tried a simple test method that encrypts and decrypts the 'abc' string with our salt and password. It works great.

```dart
Future<void> simpleTest() async {
    info('simpleTest');
    final Uint8List receivedData = 'abc'.toBytes();

    // Initialize the PBKDF2 key derivation function with the given salt and iterations
    final nc.Pbkdf2 pbkdf2 = nc.Pbkdf2(
      length: 32,
      iterations: 1000,
      salt: salt.toString().toBytes(),
      hashAlgorithm: nc.HashAlgorithm.sha256,
    );
    nc.SecretKey key = await pbkdf2(password: password);

    // Initialize the AES cipher with the derived key and GCM mode
    final nc.AES cipher = nc.AES(
      key: key,
      mode: nc.AESMode.gcm,
      padding: nc.AESPadding.none,
    );

    // Encrypt the data
    final nc.CipherText<nc.AESCipherChunk> cipherText = await cipher.encrypt(receivedData);
    
    // Create a receivedCipherText object using the encrypted data 
    // and specifying the required ivLength and tagLength
    final nc.CipherText<nc.AESCipherChunk> receivedCipherText = nc.CipherText(
      cipherText.bytes,
      chunkFactory: (bytes) => nc.AESCipherChunk(
        bytes,
        ivLength: cipher.mode.ivLength,
        tagLength: cipher.mode.tagLength,
      ),
    );

    // Decrypt the receivedCipherText to obtain the original message as Uint8List
    Uint8List message = await cipher.decrypt(receivedCipherText);

    // convert the Uint8List to a String
    String messageString = String.fromCharCodes(message);
    info('messageString: $messageString');
    info('success!');
  }
```

**Comment by riverscuomo** [comment]
@hugo-pcl Many thanks for all you've done. I am still getting this error from `cipher.decryptFile`. Do you have any thoughts?

Probably can't include the authdata on the server
```
error: PlatformException(IOException, java.io.IOException: javax.crypto.AEADBadTagException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT, Cause: javax.crypto.AEADBadTagException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT, Stacktrace: java.io.IOException: javax.crypto.AEADBadTagException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
I/flutter ( 7154): 	at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:133)
I/flutter ( 7154): 	at javax.crypto.CipherInputStream.read(CipherInputStream.java:202)
I/flutter ( 7154): 	at fr.pointcheval.native_crypto_android.ciphers.AES.decryptFile(AES.kt:138)
I/flutter ( 7154): 	at fr.pointcheval.native_crypto_android.NativeCrypto.decryptFile(NativeCrypto.kt:116)
I/flutter ( 7154): 	at fr.pointcheval.native_crypto_android.NativeCryptoAPI$Companion.setUp$lambda$22$lambda$21(Pigeon.kt:288)
I/flutter ( 7154): 	at fr.pointcheval.native_crypto_android.NativeCryptoAPI$Companion.$r8$lambda$o7wMJyBDQ0B9QInOzlOobRpTptw(Unknown Source:0)
I/flutter ( 7154): 	at fr.pointcheval.native_crypto_android.NativeCryptoAPI$Companion$$ExternalSyntheticLambda9.onMes
I/flutter ( 7154): FormatException: Unexpected character (at character 1)
I/flutter ( 7154): B9luÌ~gáz§,ëô*Ù¡:/_ev½wFÃL­ÒN²wô¾i¢Eò7C+ú»l@åa,éèÖ
```

## Encryption on the Ruby server
```ruby
def send_encrypted_file(path, "recordings.txt", password, file_mode=false, compress=true, gcm=true, sha1=false)
    ...
    # Initialize the hash object with the SHA256 algorithm
    hash =  OpenSSL::Digest::SHA256.new
    
    # Get the digest length
    len = hash.digest_length
    
    # Generate the encryption key using the password and salt
    key = OpenSSL::PKCS5.pbkdf2_hmac(password, salt, 10000, len, hash)
    
    # Create a new encryption cipher with the aes-256-gcm algorithm
    cipher = OpenSSL::Cipher.new('aes-256-gcm').encrypt
    
    # Set the cipher padding to 0
    cipher.padding = 0
    
    # Generate a random initialization vector
    iv = cipher.random_iv
    
    # Set the cipher's authentication data
    # (not supported in the new native crypto but I will remove it from the received data in the client before decryption)
    cipher.auth_data = 'REDACTED'
    
    # ...
    
    # Append the initialization vector to the data
    data << iv
    
    # Create a new deflate object with the specified options
    z = Zlib::Deflate.new(5, -15, 8, Zlib::DEFAULT_STRATEGY)
    
    # Compress the data using the deflate object
    compressed = z.deflate(path, Zlib::FINISH)
    
    # Update the encrypted data with the compressed data
    data << cipher.update(compressed)
    
    # Close the deflate object
    z.close
    
    # Finalize the encryption process
    data << cipher.final
    
    # Append the cipher's authentication tag to the data
    data << cipher.auth_tag
    
    # Set the content length header in the response
    response.headers['Content-Length'] = data.size.to_s
    
    # Send the encrypted data as a file download
    send_data(data.string, filename: filename, type: 'application/octet-stream')
  end
end
```

## Decryption on the Flutter client
```dart
/// For recordings.json
  nativeDecrypt() async {
    try {
      info('nativeDecrypt -- for recordings.json');
      _startTime = DateTime.now();
      // final receivedData = bytes.sublist(12, bytes.length); // this doesn't work
      final receivedData = bytes; // this doesn't work

      // // Remove the cipher.auth_tag (last 16 bytes) from the received data because it's no longer supported by native crypto
      // var receivedData = bytes.sublist(0, bytes.length - 16);
      // receivedData = receivedData.sublist(12, receivedData.length);

      // Write the received data to a file so we can decrypt it
      final file = File('${Core.tempPath}/$cacheFile');
      await file.writeAsBytes(receivedData, flush: true);

      // Initialize the PBKDF2 key derivation function with the given salt and iterations
      final nc.Pbkdf2 _pbkdf2 = nc.Pbkdf2(
        length: 32,
        iterations: 10000,
        salt: salt.toString().toBytes(),
        hashAlgorithm: nc.HashAlgorithm.sha256,
      );
      nc.SecretKey key = await _pbkdf2(password: password);

      // Initialize the AES cipher with the derived key and GCM mode
      final nc.AES cipher = nc.AES(
        key: key,
        mode: nc.AESMode.gcm,
        padding: nc.AESPadding.none,
      );

      // Delete the old temp file if it exists so we don't get the file already exists error
      try {
        final oldPlainTextFile = File('${Core.tempPath}/plainText.$cacheFile');
        await oldPlainTextFile.delete();
      } catch (e) {
        info('No old file to delete');
      }

      // Create a new file to store the decrypted data
      final plainTextFile = File('${Core.tempPath}/plainText.$cacheFile');

      // Decrypt the data from the file and store it in the new temp file
      await cipher.decryptFile(file, plainTextFile);

      // Read the decrypted data from the temp file
      final message = await plainTextFile.readAsBytes();

      // Delete the temp file
      await plainTextFile.delete();

      return decode(message);
    } 
    .... // catch errors
```


## Decryption with the old `native_crypto` works on the same encrypted file (as long as it's under 50mb):
```dart
oldNativeDecrypt() async{
    final data = bytes.sublist(12, bytes.length);
    final iv = bytes.sublist(0, 12);
    nc.PBKDF2 _pbkdf2 = nc.PBKDF2(keyLength: 32, iteration: 10000, hash: _sha256 ? nc.HashAlgorithm.SHA256 : nc.HashAlgorithm.SHA1);
    await _pbkdf2.derive(password: password, salt: salt);
    nc.SecretKey key = _pbkdf2.key!;
    final aad = Uint8List.fromList(AUTH_DATA.codeUnits);
    final params = nc.CipherParameters( nc.BlockCipherMode.GCM);
    nc.AESCipher aes = nc.AESCipher(key, params, aad);
    nc.CipherText cipherText = nc.AESCipherText(data, iv);
    var clearText = await aes.decrypt(cipherText);
  }
```

**Comment by hugo-pcl** [comment]
Hello, no problem ahah!

What is not yet supported by the new NativeCrypto is the authenticated data, however you should not remove the tag because it works and is necessary for decryption!

However, as you pointed out in your message, you should not add "auth_data" on the server side because you need it for decryption and it is precisely these AAD that are not supported by NativeCrypto.

The tag allows to authenticate the encrypted message (and the additional unencrypted data called AAD). But when decrypting, the AADs must also be passed to it so that the tag can be verified correctly! NativeCrypto doesn't support AADs yet, so your tag is necessarily invalid since it needs your encrypted data AND your AAD to be verified!

Is it clearer? hoping to have helped you!

**Comment by riverscuomo** [comment]
It looks like my colleague has solved this for us. I will try to come back later with more details. But basically we are using the old `native crypto` and have modified both the server and the client so they are matching perfectly. We are able to download large files without a memory error. Thanks for all your help @hugo-pcl !

**Comment by greg0x** [comment]
I wanted to thank both of you for this wonderful thread. It was a tremendous help to get into the lib, the cryptography and the overall problem. 

We ended up sticking with the old version for of the api support but implemented your original recommendation. 
> Fix the server-side encryption: encrypt the X bytes chunks independently of the others to be the same format as NativeCrypto. And be consistent with the size of the NativeCrypto chunks you will decrypt on the client side (you can configure the size when you initialize the NativeCrypto [AES cipher](https://github.com/hugo-pcl/native-crypto-flutter/blob/cab2843706fa8f0ce71aef15a5d134713b9a4326/packages/native_crypto/lib/src/ciphers/aes/aes.dart#L38))

The quality of this project is something I rarely encounter. I was amazed. 
Thank you for this amazing work!
