### ISSUE TITLE
Alignment of aes encrypted files

### ISSUE THREAD

**Issue by andrewfam** [hugo-pcl/native-crypto-flutter#6]
I've found this coming from pointycastle and have files already encrypted using pointycastle with the code exactly as your repo. How do i align the files such that the encryption / decryption works with this?

I'm currently getting an error where the bytes is null from decrypting preexisting files

if (bytes == null) {
      throw NativeCryptoException(
        code: NativeCryptoExceptionCode.nullError,
        message: 'Platform returned null bytes on chunk #$count',
      );
    }

**Comment by hugo-pcl** [comment]
Hello,

Thank you for reaching out with your issue regarding the decryption of pre-existing files using NativeCrypto.

In NativeCrypto, encrypted payloads are by default considered as 'chunked.' This means that when you encrypt a payload using NativeCrypto, it is divided into chunks of 32MB each. Each chunk follows the format outlined in the README: `Nonce (12 bytes) | Cipher text (n-28) | Tag (16 bytes)`. This chunking mechanism is due to a system limitation in the data transfer between the native layer and the Flutter layer, and vice versa.

To decrypt content that was encrypted externally (i.e., not using NativeCrypto's chunking mechanism), you need to modify the chunk size to accommodate the entire encrypted payload. Otherwise, decryption will fail because the external encrypted data was not pre-divided into these specific chunks.

```dart
// Initialize an AES cipher
final AES cipher = AES(
    key: secretKey,
    mode: AESMode.gcm,
    padding: AESPadding.none,
    chunkSize: // <- here
);
```

**But if you wish to encrypt/decrypt without worrying about this chunking system**, I recommend using the file decryption method. By simply providing a file path to the native layer, you can bypass the chunking mechanism and decrypt your file as a whole. https://github.com/hugo-pcl/native-crypto-flutter/blob/cab2843706fa8f0ce71aef15a5d134713b9a4326/packages/native_crypto/example/lib/data/data_sources/native_crypto_data_source_impl.dart#L35C2-L56C4

This approach should resolve the issue of null bytes being returned during decryption of pre-existing files.

Hope to have helped you. Don't hesitate if you have any other questions!

**Comment by andrewfam** [comment]
Thanks for this. setting the chunk size still returns the null error for some files.
static Future<Uint8List> fileDecryptAESGCM(
      {required Uint8List bytes,
      required String archiveKey,
      required Uint8List iv}) async {
    BugfenderHelper.sendLog(BugfenderHelper.getMessage(
        key: BugFenderLogKeys.startCallFunction,
        params: ['NativeEncryptHelper.fileDecryptAESGCM']));

    final SecretKey secretKey = SecretKey(utils.HexUtils.decode(archiveKey));
    final fullData = Uint8List.fromList(iv + bytes);

    final AES cipher = AES(
        key: secretKey,
        mode: AESMode.gcm,
        padding: AESPadding.none,
        chunkSize: fullData.lengthInBytes);

    final Uint8List decryptedFileBytes = await cipher.decrypt(
      CipherText(
        fullData,
        chunkFactory: (chunk) => AESCipherChunk(
          chunk,
          ivLength: 16,
          tagLength: 16,
        ),
      ),
    );

    return Uint8List.fromList(decryptedFileBytes);
  }
